num_turns: 5
num_samples: 1
model_name: "claude-sonnet-4-20250514"
agents:
  - name: "Claude 1"
    system_prompt: "You are a helpful AI talking with another helpful AI"
  
  - name: "Claude 2"
    system_prompt: "You are a helpful AI talking with another helpful AI"